import '../icons/heart.svg'
import '../icons/logo.svg'
import '../icons/profile.svg'
import '../icons/search.svg'

import '../styles/style.scss'
import '../icons/slider.jpg'
import '../icons/slider.webp'
import '../icons/slider@2x.jpg'
import '../icons/slider@2x.webp'